### ISSUE TITLE
Linux Setup

### ISSUE THREAD

**Issue by elixirgm** [fearedbliss/Cactus#11] opened 2024-05-11 13:34 UTC
*edited for a little clarity, I hope*

Hey there, first I'd like to give a big thumbs up as I have used cactus in the past and it worked well.  I much prefer it to D2SE or other alternatives.  I recently moved to linux due to how  bad Windows 11 is and  I  am having one tiny little issue I simply may be overlooking.

It seems using patches prior to the no cd fix aren't running.  
My understanding with how much people set that up is patching d2gfx or or potentially other files.  Already having them in the platform should be enough i'd imagine.

The MPQ fix as described mentions patching to prior versions when installing with the new installer.  I question if without that fix the game isn't picking up on the change within those files?

I am not sure how to run a bat as admin through wine.  IVe tried googling and seem to get nowhere.  I have run the bat inside the wine prefix in desktop mode to confirm it even ran and it DID, I can't see any physical changes to the files and earlier versions are prompting for CD.    

I'd imagine I can simply utilize other methods to override these files as I have edited  files on my backup harddrive, however reducing the number of steps simply by using cactus as a 1 off would be better for helping others setup D2 on linux.   

No rush, I have figured out isolating versions with separate directories, my individual file overrides, and using links for streamlining my savefolder sync for the time being. I may also very well accidentally figure it out as I continue to play with and learn more on how wine works.  

Thank you for your work!

**Comment by fearedbliss** [comment] 2024-05-18 13:47
Hey @elixirgm, I'm glad you've been enjoying Cactus :).

As mentioned in the compatibility of the project, Cactus is only supported for Windows 7 and Windows 10 (I'm also done with Microsoft and their shenanigans, and Windows 11 is a no-go for me for many reasons, the worst ones which are stated here: https://github.com/fearedbliss/Cactus?tab=readme-ov-file#windows-11-will-not-be-supported).

This also means Linux is not supported even though I personally use FreeBSD on all of my machines (excluding my Windows 10 gaming computer which is not connected to the internet. So just Offline Single Player DRM free games for me). So yea, don't try to run Cactus through Wine lol.

I can try and give you some basic advice. 

1. Regarding running BAT files on UNIX-like systems, I haven't tried to do this so not sure how or if you would even get the expected behavior. One workaround would be to run an older version of Windows in a VM, fix the MPQs in there, and then just back those MPQs up and use them on Linux.
2. The `d2gfx.dll` is responsible for providing multiple instance support.
3. The `Game.exe` is responsible for No CD. All Cactus platforms include `No CD` by default, so if you are using the Cactus platforms, all of them will already have this for you, and you don't need to worry about it.
4. The MPQ fixer is what will allow the game to launch without receiving a corrupt MPQ message for versions between 1.08 - 1.13d. This is stated here: https://github.com/fearedbliss/Cactus?tab=readme-ov-file#required-files

The workaround I used when I did try it on UNIX systems was to basically have separate folders for each Platform, alongside with manually creating separate Save directories, then I would manually change the files to a common "root" directory, essentially simulating what Cactus is doing/Diablo II expects, and finally I would manually change the WINEPREFIX to a D2 specific one, alongside with modifying the registry for that particular prefix to point to the correct `SavePath`, `NewSavePath`, etc.

A fellow community member at The Moving Caravan made this script for Linux, which you may find useful:

https://themovingcaravan.com/threads/linux-version-switch-script.94/

Hopefully that guides you in the right direction. Closing this since it isn't a Cactus issue.

**Closed by fearedbliss** 2024-05-18 13:47 UTC
